### ISSUE TITLE
Signin.vue component is not displaying properly

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi-frontend#1]
@mhaidarh 

Please refer to [this file](https://github.com/gunadarma-academy/asde-michi-frontend/blob/master/src/components/Signin.vue) and see if you can come up with a solution. Thanks.

**Comment by mhaidarhanif** [comment]
@ekkyvalent I will try to inspect it.

**Comment by ekkyvalent** [comment]
@mhaidarh I find a solution, I will close the issue as soon as I commit the changes.

**Comment by mhaidarhanif** [comment]
@ekkyvalent Nice :+1:
