### ISSUE TITLE
Problems with Question.vue layout 

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi-frontend#2]
A little layout problem on the [Question.vue component](https://github.com/gunadarma-academy/asde-michi-frontend/blob/master/src/components/Question.vue) where the `mdl-card` card shows no padding with the text inside.

**Comment by mhaidarhanif** [comment]
@ekkyvalent Will try to inspect it too.

**Comment by mhaidarhanif** [comment]
@ekkyvalent Where this component is used?

**Comment by ekkyvalent** [comment]
@mhaidarh It's not yet implemented but rather temporarily routed (I guess).

**Comment by ekkyvalent** [comment]
This fixed for now.
