### ISSUE TITLE
Anchor element with v-link is not working properly

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi-frontend#3]
Refer to [this component](https://github.com/gunadarma-academy/asde-michi-frontend/blob/master/src/components/Landing.vue). Anchor link appears to be unclickable (for lack of better words).

**Comment by mhaidarhanif** [comment]
@ekkyvalent Will try to inspect it too.

**Comment by mhaidarhanif** [comment]
Unfortunately `v-link` doesn't work with `<button>`
